import ProjectDescription

let workspace = Workspace(
    name: "InnoSample",
    projects: [
        .relativeToRoot("App"),
        .relativeToRoot("Cores/**"),
        .relativeToRoot("Layers/**"),
        .relativeToRoot("ThirdParties/**"),
        .relativeToRoot("Utils/**"),
        .relativeToRoot("Features/**"),
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
