@testable import Domain
@testable import EntireTabFeatureRouter
import EntireTabFeatureTesting
import Foundation
import PeopleFeatureInterface
@testable import PeopleFeatureRouter
import PostsFeatureInterface
@testable import PostsFeatureRouter
import SettingsFeatureInterface
@testable import SettingsFeatureRouter
import Testing

@Suite("Entire tab feature")
@MainActor
struct EntireTabFeatureTests {
    @Test("tab metadata is generated by Router macros")
    func macroGeneratedTabs() {
        #expect(SampleTab.allCases == [.people, .posts, .settings])
        #expect(EntireTabFeatureFixtures.tabCount == SampleTab.allCases.count)
    }

    @Test("people-to-settings navigation returns a typed tab intent")
    func mediatesPeopleToSettingsNavigation() {
        let coordinator = makeCoordinator()

        coordinator.peopleCoordinator.openSettings(for: .init(assigneeID: 1))
        let tab = coordinator.consumeCrossFeatureNavigationFromPeople()

        #expect(tab == .settings)
        #expect(
            coordinator.settingsCoordinator.model.activityLog.contains(
                "queued external navigation for assignee #1"
            )
        )
    }

    @Test("settings-to-people navigation returns a typed tab intent")
    func mediatesSettingsToPeopleNavigation() {
        let coordinator = makeCoordinator()

        coordinator.settingsCoordinator.openPeople(for: .init(userID: 1))
        let tab = coordinator.consumeCrossFeatureNavigationFromSettings()

        #expect(tab == .people)
        #expect(
            coordinator.peopleCoordinator.model.activityLog.contains(
                "queued external navigation for user #1"
            )
        )
    }

    @Test("DeepLink macro resolves typed payloads")
    func generatedDeepLinkResolver() throws {
        let settingsURL = try #require(URL(string: "innosample://host/settings/3"))
        let peopleURL = try #require(URL(string: "innosample://host/people/42"))

        #expect(SampleDeepLink.resolveDeepLink(settingsURL) == .settingsDetail(assigneeID: 3))
        #expect(SampleDeepLink.resolveDeepLink(peopleURL) == .peopleDetail(userID: 42))
    }

    @Test("DeepLink macro rejects unknown paths, payloads, and origins")
    func generatedDeepLinkResolverRejectsInvalidURLs() throws {
        let unknown = try #require(URL(string: "innosample://host/unknown"))
        let invalidID = try #require(URL(string: "innosample://host/settings/not-a-number"))
        let missingID = try #require(URL(string: "innosample://host/people"))
        let foreignOrigin = try #require(URL(string: "https://host/settings/1"))

        #expect(SampleDeepLink.resolveDeepLink(unknown) == nil)
        #expect(SampleDeepLink.resolveDeepLink(invalidID) == nil)
        #expect(SampleDeepLink.resolveDeepLink(missingID) == nil)
        #expect(SampleDeepLink.resolveDeepLink(foreignOrigin) == nil)
    }

    @Test("deep-link dispatch returns the tab selected by EnvironmentRouter")
    func handlesSettingsDeepLink() throws {
        let coordinator = makeCoordinator()
        let url = try #require(URL(string: "innosample://host/settings/1"))

        #expect(coordinator.handleDeepLink(url) == .settings)
        #expect(
            coordinator.settingsCoordinator.model.activityLog.contains(
                "queued external navigation for assignee #1"
            )
        )
    }

    private func makeCoordinator() -> EntireTabCoordinator {
        let peopleInput = PeopleFeatureInput(
            fetchPeopleUseCase: FetchPeopleUseCase(
                repository: StubUserRepository(users: Self.users)
            )
        )

        return EntireTabCoordinator(
            peopleCoordinator: .init(
                input: peopleInput,
                detailFactory: PeopleDetailContainer.AssistedFactory(
                    input: peopleInput
                )
            ),
            postsCoordinator: .init(
                input: .init(
                    fetchPostsUseCase: FetchPostsUseCase(
                        repository: StubPostRepository(posts: Self.posts)
                    )
                )
            ),
            settingsCoordinator: .init(
                input: .init(
                    fetchTodosUseCase: FetchTodosUseCase(
                        repository: StubTodoRepository(todos: Self.todos)
                    )
                )
            )
        )
    }

    private static let users: [UserSummary] = [
        .init(
            id: 1,
            name: "Leanne Graham",
            username: "Bret",
            email: "leanne@example.com",
            phone: "010-0000-0001",
            website: "leanne.dev",
            company: "InnoSquad",
            city: "Seoul"
        )
    ]

    private static let posts: [PostSummary] = [
        .init(id: 100, title: "Post", body: "Body", authorID: 1)
    ]

    private static let todos: [TodoSummary] = [
        .init(id: 200, title: "Todo for Leanne", completed: false, assigneeID: 1)
    ]
}

private struct StubUserRepository: UserRepositoryProtocol {
    let users: [UserSummary]
    func fetchUsers() async throws -> [UserSummary] { users }
}

private struct StubPostRepository: PostRepositoryProtocol {
    let posts: [PostSummary]
    func fetchPosts() async throws -> [PostSummary] { posts }
}

private struct StubTodoRepository: TodoRepositoryProtocol {
    let todos: [TodoSummary]
    func fetchTodos() async throws -> [TodoSummary] { todos }
}
